apiVersion: apps/v1
kind: Deployment
metadata:
  name: counsel
  labels:
    app: counsel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counsel
  template:
    metadata:
      labels:
        app: counsel
    spec:
      containers:
        - name: counsel
          image: 879772956301.dkr.ecr.ca-central-1.amazonaws.com/user18-lectureydjeon-counsel:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/counsels'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/counsels'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
